from enum import Enum
class DataFormats(str, Enum):
    JSON = "json"
    CSV = "csv"
    PARQUET = "parquet"
    TXT = "txt"
    XLSX = "xlsx"
    XLS = "xls"
    DELTA = "delta"
    DA2 = "da2"
    DAT = "dat"
class DefaultDelimiters(str, Enum):
    WSP = "0x00"
    ETX = "0x03"
    STX = "0x02"
    COMMA = "0x2c"
    QUOTES = "0x22"
    TAB = "0x2c"
    BACKSLASH = "0x5c"
    LF = "0x0a"
    UTF_8 = "utf-8"
class StatusEnum(str, Enum):
    IN_PROGRESS = "In Progress"
    DONE = "Done"
    FAILED = "Failed"
    STOPPED = "Stopped"
    PENDING_REVIEW = "Pending Review"
    APPROVED = "Approved"
    REJECTED = "Rejected"
    QUEUED = "Queued"
    ERRORED = "Errored"
    ERROR = "Error"
    ACTIVE = "Active"
    INACTIVE = "Inactive"
    PENDING = "Pending"
    NOT_STARTED = "Not Started"
    MAPPING_UNAVAILABLE = "Mapping Unavailable"
    ALL_RECORDS_DROPPED = "All Records Dropped"
    PARTIALLY_DONE = "Partially Done"
class SourceTargetTypes(str, Enum):
    S3 = "s3"
    DELTALAKE = "deltalake"
    INFOR_DATALAKE = "infor-datalake"
    MONGO = "mongo"
    MS_SQL = "mssql"
    ORACLE = "oracle"
    POSTGRESQL = "postgresql"
    SNOWFLAKE = "snowflake"
    IBM_DB2 = "ibmdb2"
class Environments(str, Enum):
    DEVELOPMENT = "development"
    PRODUCTION = "production"
class DataMeshOperations(str, Enum):
    M3_VALIDATION = "M3 Validation"
    TRANSFORMATION = "Transformation"
    MASTER_MATCH = "Master Match"
    MASTER_SPLIT = "Master Split"
    MASTER_MERGE = "Master Merge"
    PROFILING = "Profiling"
    COMPARE_ANALYSIS = "Compare Analysis"
    INTEGRITY_ANALYSIS = "Integrity Analysis"
    SEQUENCE_GENERATOR = "Sequence Generator"
    FILTER = "Filter"
    INFOR_DATALAKE_EXTRACTION = "Infor Datalake Extraction"
    JOIN = "Join"
    UNION = "Union"
    DEDUPE = "De-duplication"
    INSPECT_AND_REPAIR = "Inspect and Repair"
New code
    UNZIP = "Unzip"
    EXCEL_TO_CSV = "Excel to Csv"
    CSV_TO_EXCEL = "Csv to Excel"
    TEXT_TO_CSV = "Text to Csv"
    DETECT_ENCODING = "Detect Encoding"
    SPLIT_FILES = "Split Files"
    SUGGESTIONS = "Suggestions"
    CHECKS = "Checks"
    ANALYZERS = "Analyzers"
    COMPARE_CONFIGURATIONS = "Compare Configurations"
    LOAD_READY = "Load Ready"
    THIRD_PARTY_INTEGRATIONS = "Third Party Integrations"
    INGEST = "Data Ingestion"
    SQL_QUERY = "SQL Query"
class IncrementalReadOption(str, Enum):
    NO = "N"
    YES = "Y"
class SourceSystems(str, Enum):
    BAAN = "baan"
    LN = "ln"
Uncovered code
class Versions(str, Enum):
    V1 = "v1"
    V2 = "v2"